import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '@/context';
import SearchBar from '@/Components/section-header/SearchBar';
import ButtonToOpenBagShopping from '@/Components/Bag-shopping-components/button';
require('dotenv').config();

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import './style-page.css';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <SearchBar />
          </header>
          <ButtonToOpenBagShopping />
          {children}
        </body>
      </html>
    </Providers>
  );
}
