import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SearchBar from '@/Components/section-header/SearchBar';
import ShoppingCart from '@/Components/section-product-cart/product-cart';
require('dotenv').config();

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import './style-page.css';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <SearchBar />
        </header>
        <ShoppingCart />
        {children}
      </body>
    </html>
  );
}
